org.gradle.jvmargs=-Xmx2G
org.gradle.daemon=false
org.gradle.configuration-cache=true

mod_id=atmons_spawn_controller
mod_name=All the Mons Spawn Controller
mod_version=0.1.0
mod_group_id=io.github.jan-guenter
repository_name=allthemons-spawn-controller
minecraft_version=1.21.1
neoforge_version=21.1.234
